image: python:3-alpine

before_script:
  - apk update
  - apk add zip

stages:
  - test
  - build

test:
  stage: test
  script:
    - python -mjson.tool 'fxmaster/module.json' > /dev/null

build:
  stage: build
  script:
    - zip fxmaster.zip -r fxmaster -x ".*"
  artifacts:
    name: fxmaster
    when: on_success
    paths:
      - fxmaster.zip
  when: on_success
  only:
    - tags
    - master
